"""
工具注册表 — 所有可用的 Tool 定义，供 AI 编排工作流和可视化构建器使用。
每个 Tool 定义了 id / name / description / inputs / outputs / config_schema / icon / color。
"""

TOOLS = [
    {
        "id": "user_input",
        "name": "User Input 用戶輸入",
        "description": "輸入文字或上傳文件作為工作流起點",
        "icon": "📝", "color": "#6366f1",
        "inputs": [],
        "outputs": ["text"],
        "output_labels": {"text": "輸入內容"},
        "category": "input",
        "config_schema": [],
    },
    {
        "id": "meeting_recorder",
        "name": "Meeting Notes 會議記錄",
        "description": "录音/上传音频 → 转写为文本（transcript）→ AI 生成会议总结（summary）",
        "icon": "🎙️", "color": "#6366f1",
        "inputs": [],
        "outputs": ["recording", "transcript", "summary"],
        "output_labels": {"recording": "录音文件", "transcript": "对话记录", "summary": "会议总结"},
        "category": "input",
        "config_schema": [
            {"key": "mode", "label": "会议模式", "type": "select", "options": [
                {"label": "🎤 现场会议", "value": "live"},
                {"label": "💻 线上会议", "value": "online"},
            ]},
        ],
    },
    {
        "id": "document_summary",
        "name": "Document Summary 文件摘要",
        "description": "对输入文本进行 AI 摘要",
        "icon": "📄", "color": "#3b82f6",
        "inputs": ["text"],
        "outputs": ["summary"],
        "output_labels": {"summary": "摘要"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "mindmap",
        "name": "AI Mind Map 思維導圖",
        "description": "将文本转换为 Markdown 思维导图",
        "icon": "🧠", "color": "#ec4899",
        "inputs": ["text"],
        "outputs": ["markdown"],
        "output_labels": {"markdown": "思维导图"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "todo_extraction",
        "name": "Todo Extract 待办提取",
        "description": "从文本中提取结构化待办事项",
        "icon": "✅", "color": "#10b981",
        "inputs": ["text"],
        "outputs": ["todos"],
        "output_labels": {"todos": "待办列表"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "todo_add",
        "name": "Add Todo 添加待办",
        "description": "将待办事项写入数据库",
        "icon": "➕", "color": "#f59e0b",
        "inputs": ["todos"],
        "outputs": ["added_count"],
        "output_labels": {"added_count": "已添加数量"},
        "category": "output",
        "config_schema": [],
    },
    {
        "id": "email_doc",
        "name": "Email & Document Generator 郵件公文生成",
        "description": "根据提示生成邮件/公文/报告",
        "icon": "✉️", "color": "#06b6d4",
        "inputs": ["text"],
        "outputs": ["document"],
        "output_labels": {"document": "文档"},
        "category": "output",
        "config_schema": [
            {"key": "doc_mode", "label": "文档类型", "type": "select", "options": [
                {"label": "Email 邮件", "value": "email"},
                {"label": "Official 公文", "value": "official"},
                {"label": "Report 报告", "value": "report"},
                {"label": "Notice 通知", "value": "notice"},
            ]},
            {"key": "to", "label": "收件人", "type": "text", "placeholder": "可选"},
        ],
    },
    {
        "id": "translation",
        "name": "Translation 翻译写作",
        "description": "翻译/润色/改写文本",
        "icon": "🌐", "color": "#8b5cf6",
        "inputs": ["text"],
        "outputs": ["translated_text"],
        "output_labels": {"translated_text": "翻译结果"},
        "category": "process",
        "config_schema": [
            {"key": "mode", "label": "模式", "type": "select", "options": [
                {"label": "中→英", "value": "translate_zh_en"},
                {"label": "英→中", "value": "translate_en_zh"},
                {"label": "润色", "value": "polish"},
                {"label": "改写", "value": "rewrite"},
                {"label": "扩写", "value": "expand"},
                {"label": "摘要", "value": "summarize"},
            ]},
        ],
    },
    {
        "id": "ppt_outline",
        "name": "PPT / HTML Generator 簡報生成",
        "description": "根据主题生成 PPT 大纲",
        "icon": "📽️", "color": "#ef4444",
        "inputs": ["text"],
        "outputs": ["outline"],
        "output_labels": {"outline": "PPT大纲"},
        "category": "output",
        "config_schema": [
            {"key": "slides", "label": "页数", "type": "number"},
            {"key": "style", "label": "风格", "type": "text", "placeholder": "如：极简、数据驱动..."},
        ],
    },
    {
        "id": "deep_research",
        "name": "Deep Research 深度调研",
        "description": "网络搜索并生成研究报告",
        "icon": "🔍", "color": "#14b8a6",
        "inputs": ["text"],
        "outputs": ["report", "sources"],
        "output_labels": {"report": "调研报告", "sources": "来源"},
        "category": "output",
        "config_schema": [],
    },
    {
        "id": "weekly_report",
        "name": "Weekly Report 周报",
        "description": "根据工作要点生成周报",
        "icon": "📊", "color": "#f59e0b",
        "inputs": ["text"],
        "outputs": ["report"],
        "output_labels": {"report": "周报"},
        "category": "output",
        "config_schema": [],
    },
    {
        "id": "data_analysis",
        "name": "Data Analysis 数据分析",
        "description": "对 CSV/Excel 数据进行分析",
        "icon": "📈", "color": "#3b5ccc",
        "inputs": ["file"],
        "outputs": ["result", "chart"],
        "output_labels": {"result": "分析结果", "chart": "图表"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "task_planning",
        "name": "Task Planning 任务规划",
        "description": "拆解任务、估算时间、识别依赖",
        "icon": "🗓️", "color": "#e11d48",
        "inputs": ["text"],
        "outputs": ["plan"],
        "output_labels": {"plan": "规划结果"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "document_comparison",
        "name": "Doc Compare 文件对比",
        "description": "对比两份文档的差异",
        "icon": "⚖️", "color": "#a855f7",
        "inputs": ["text_a", "text_b"],
        "outputs": ["diff"],
        "output_labels": {"diff": "差异报告"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "multi_source_reader",
        "name": "Multi-Source 多源阅读",
        "description": "整合多个来源的信息并输出综合报告",
        "icon": "📖", "color": "#65a30d",
        "inputs": ["text"],
        "outputs": ["report"],
        "output_labels": {"report": "综合报告"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "spreadsheet",
        "name": "Spreadsheet AI 智能表格",
        "description": "上传表格并用自然语言操作",
        "icon": "📊", "color": "#22c55e",
        "inputs": ["file"],
        "outputs": ["result"],
        "output_labels": {"result": "操作结果"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "rag_qa",
        "name": "Knowledge Q&A 知识库问答",
        "description": "基于本地知识库回答问题",
        "icon": "📚", "color": "#f97316",
        "inputs": ["text"],
        "outputs": ["answer", "sources"],
        "output_labels": {"answer": "答案", "sources": "来源"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "image_analyzer",
        "name": "Image Analyzer 圖片分析",
        "description": "上傳圖片，AI 分析內容、物體、色彩、文字",
        "icon": "🖼️", "color": "#ec4899",
        "inputs": [],
        "outputs": ["description", "objects", "style", "text_in_image"],
        "output_labels": {"description": "圖片描述", "objects": "物體列表", "style": "風格", "text_in_image": "圖中文字"},
        "category": "input",
        "config_schema": [],
    },
    {
        "id": "chart_generator",
        "name": "Chart Generator 圖表生成",
        "description": "輸入數據，AI 生成 matplotlib 可視化圖表",
        "icon": "📊", "color": "#22c55e",
        "inputs": ["text"],
        "outputs": ["chart_url", "result"],
        "output_labels": {"chart_url": "圖表圖片", "result": "生成結果"},
        "category": "output",
        "config_schema": [
            {"key": "chart_type", "label": "圖表類型", "type": "select", "options": [
                {"label": "📊 Bar 柱狀圖", "value": "bar"},
                {"label": "📈 Line 折線圖", "value": "line"},
                {"label": "🥧 Pie 餅圖", "value": "pie"},
                {"label": "📍 Scatter 散點圖", "value": "scatter"},
            ]},
            {"key": "title", "label": "標題", "type": "text", "placeholder": "圖表標題"},
        ],
    },
    {
        "id": "table_generator",
        "name": "Table Generator 表格生成",
        "description": "從報告或文字中提取結構化表格數據，輸出CSV格式",
        "icon": "📋", "color": "#3b82f6",
        "inputs": ["text"],
        "outputs": ["table_csv", "table_result"],
        "output_labels": {"table_csv": "表格CSV數據", "table_result": "生成結果"},
        "category": "process",
        "config_schema": [
            {"key": "columns", "label": "列名（逗號分隔）", "type": "text", "placeholder": "如：年份,安踏營收,李寧營收"},
            {"key": "hint", "label": "提取要求", "type": "text", "placeholder": "如：提取近五年營收利潤數據"},
        ],
    },
    {
        "id": "pdf_toolkit",
        "name": "PDF Toolkit PDF工具",
        "description": "合併、拆分、提取PDF文字",
        "icon": "📑", "color": "#ef4444",
        "inputs": [],
        "outputs": ["text", "url"],
        "output_labels": {"text": "提取文字", "url": "文件鏈接"},
        "category": "input",
        "config_schema": [
            {"key": "action", "label": "操作", "type": "select", "options": [
                {"label": "📄 提取文字", "value": "extract"},
                {"label": "🔗 合併PDF", "value": "merge"},
                {"label": "✂️ 拆分PDF", "value": "split"},
            ]},
        ],
    },
    {
        "id": "sentiment_analyzer",
        "name": "Sentiment Analyzer 情感分析",
        "description": "分析文本情感：正面/負面/中性",
        "icon": "💬", "color": "#8b5cf6",
        "inputs": ["text"],
        "outputs": ["sentiment", "confidence", "scores"],
        "output_labels": {"sentiment": "情感結果", "confidence": "信心度", "scores": "詳細分數"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "web_scraper",
        "name": "Web Scraper 網頁抓取",
        "description": "輸入URL，自動提取網頁正文內容",
        "icon": "🕷️", "color": "#f97316",
        "inputs": ["text"],
        "outputs": ["scraped_text"],
        "output_labels": {"scraped_text": "網頁內容"},
        "category": "input",
        "config_schema": [],
    },
    {
        "id": "qr_generator",
        "name": "QR Generator 二維碼",
        "description": "將文字或連結生成為QR碼圖片",
        "icon": "📱", "color": "#6366f1",
        "inputs": ["text"],
        "outputs": ["qr_url"],
        "output_labels": {"qr_url": "QR碼圖片"},
        "category": "output",
        "config_schema": [
            {"key": "size", "label": "尺寸", "type": "number", "placeholder": "300"},
        ],
    },
    {
        "id": "calculator",
        "name": "Calculator 計算器",
        "description": "安全計算四則/冪/括號表達式，如 (8+2)*5/2",
        "icon": "🧮", "color": "#22c55e",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "計算結果"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "date_calc",
        "name": "Date Calc 日期計算",
        "description": "解析相對日期：今天/明天/下周五/N天后/N月后",
        "icon": "📅", "color": "#3b82f6",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "日期結果"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "unit_converter",
        "name": "Unit Converter 單位換算",
        "description": "長度/重量/溫度/數據量單位換算，如 5公里等于多少英里",
        "icon": "⚖️", "color": "#f59e0b",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "換算結果"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "word_counter",
        "name": "Word Count 字數統計",
        "description": "中英混合字數統計（中文字符+英文單詞）",
        "icon": "🔢", "color": "#8b5cf6",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "統計結果"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "json_formatter",
        "name": "JSON Formatter JSON格式化",
        "description": "格式化或校驗 JSON 文本",
        "icon": "🧾", "color": "#ec4899",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "格式化結果"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "weather",
        "name": "Weather 天氣查詢",
        "description": "查詢城市當前天氣（open-meteo，免 API key）",
        "icon": "🌤️", "color": "#06b6d4",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "天氣信息"},
        "category": "process",
        "config_schema": [
            {"key": "city", "label": "城市", "type": "text", "placeholder": "如：北京"},
        ],
    },
    {
        "id": "exchange_rate",
        "name": "Exchange Rate 匯率查詢",
        "description": "查詢實時匯率（open.er-api.com，免 API key）",
        "icon": "💱", "color": "#14b8a6",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "匯率信息"},
        "category": "process",
        "config_schema": [
            {"key": "base", "label": "源貨幣", "type": "text", "placeholder": "USD"},
            {"key": "target", "label": "目標貨幣", "type": "text", "placeholder": "CNY"},
        ],
    },
    {
        "id": "stock_quote",
        "name": "Stock Quote 股價查詢",
        "description": "查詢股票價格（需配置 STOCK_API_KEY）",
        "icon": "📈", "color": "#ef4444",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "股價信息"},
        "category": "process",
        "config_schema": [
            {"key": "symbol", "label": "股票代碼", "type": "text", "placeholder": "AAPL"},
        ],
    },
    {
        "id": "stock_predictor",
        "name": "Stock Predictor 股票預測",
        "description": "sklearn 線性/邏輯回歸預測次日收盤價與漲跌方向（教學示例，不構成投資建議）",
        "icon": "📉", "color": "#f97316",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "預測結果"},
        "category": "process",
        "config_schema": [
            {"key": "close", "label": "今日收盤價", "type": "number", "placeholder": "可選，缺省用最新數據"},
        ],
    },
    {
        "id": "fruit_classifier",
        "name": "Fruit Classifier 水果識別",
        "description": "KNN 分類水果（質量/寬度/高度/顏色分數），教學示例",
        "icon": "🍎", "color": "#22c55e",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "識別結果"},
        "category": "process",
        "config_schema": [
            {"key": "mass", "label": "質量(克)", "type": "number"},
            {"key": "width", "label": "寬度(厘米)", "type": "number"},
            {"key": "height", "label": "高度(厘米)", "type": "number"},
            {"key": "color_score", "label": "顏色分數(0~1)", "type": "number"},
        ],
    },
    {
        "id": "spam_classifier",
        "name": "Spam Detector 垃圾郵件檢測",
        "description": "隨機森林判斷郵件/短信是否垃圾（關鍵詞+長度等特徵），教學示例",
        "icon": "🚫", "color": "#ef4444",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "判斷結果"},
        "category": "process",
        "config_schema": [],
    },
    {
        "id": "priority_classifier",
        "name": "Task Priority 任務優先級",
        "description": "決策樹判斷任務優先級（截止日期/影響/領導跟進/工作量），可解釋 if-then 規則",
        "icon": "🎯", "color": "#8b5cf6",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "優先級結果"},
        "category": "process",
        "config_schema": [
            {"key": "deadline", "label": "截止日期", "type": "select", "options": [
                {"label": "寬鬆", "value": 0}, {"label": "正常", "value": 1}, {"label": "緊急", "value": 2}]},
            {"key": "impact", "label": "影響範圍", "type": "select", "options": [
                {"label": "低", "value": 0}, {"label": "中", "value": 1}, {"label": "高", "value": 2}]},
            {"key": "leader_followup", "label": "領導跟進", "type": "select", "options": [
                {"label": "否", "value": 0}, {"label": "是", "value": 1}]},
            {"key": "workload", "label": "工作量", "type": "select", "options": [
                {"label": "小", "value": 0}, {"label": "中", "value": 1}, {"label": "大", "value": 2}]},
        ],
    },
    {
        "id": "delay_risk",
        "name": "Delay Risk 延期風險檢測",
        "description": "梯度提升樹判斷項目延期風險（進度/人手/需求變更/加班/依賴/臨時需求）",
        "icon": "⏰", "color": "#f97316",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "風險結果"},
        "category": "process",
        "config_schema": [
            {"key": "plan_progress", "label": "計劃進度", "type": "select", "options": [
                {"label": "落後", "value": 0}, {"label": "正常", "value": 1}, {"label": "超前", "value": 2}]},
            {"key": "manpower_shortage", "label": "人手缺口", "type": "select", "options": [
                {"label": "充足", "value": 0}, {"label": "不足", "value": 1}]},
            {"key": "req_change", "label": "需求變更", "type": "select", "options": [
                {"label": "很少變更", "value": 0}, {"label": "經常改需求", "value": 1}]},
            {"key": "overtime_freq", "label": "加班頻率", "type": "select", "options": [
                {"label": "幾乎不", "value": 0}, {"label": "偶爾", "value": 1}, {"label": "天天", "value": 2}]},
            {"key": "depend_task", "label": "外部依賴", "type": "select", "options": [
                {"label": "無", "value": 0}, {"label": "有", "value": 1}]},
            {"key": "urgent_boss", "label": "老闆臨時需求", "type": "select", "options": [
                {"label": "沒有", "value": 0}, {"label": "有", "value": 1}]},
        ],
    },
    {
        "id": "attrition_risk",
        "name": "Attrition Risk 離職風險預測",
        "description": "FCN 全連接網路預測員工離職風險（工齡/薪資/加薪/績效/加班/晉升間隔/部門/年齡/考勤）",
        "icon": "👋", "color": "#14b8a6",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "離職風險結果"},
        "category": "process",
        "config_schema": [
            {"key": "tenure", "label": "工齡(年)", "type": "number"},
            {"key": "salary", "label": "月薪資(元)", "type": "number"},
            {"key": "raise_pct", "label": "最近加薪幅度(%)", "type": "number"},
            {"key": "performance", "label": "績效評分(1~5)", "type": "number"},
            {"key": "overtime_hours", "label": "月加班時長(小時)", "type": "number"},
            {"key": "months_since_promotion", "label": "距上次晉升(月)", "type": "number"},
            {"key": "department", "label": "部門", "type": "select", "options": [
                {"label": "技術部", "value": "技术部"},
                {"label": "銷售部", "value": "销售部"},
                {"label": "市場部", "value": "市场部"},
                {"label": "財務部", "value": "财务部"},
                {"label": "人事部", "value": "人事部"},
                {"label": "運營部", "value": "运营部"},
            ]},
            {"key": "age", "label": "年齡", "type": "number"},
            {"key": "attendance_anomalies", "label": "考勤異常次數", "type": "number"},
        ],
    },
    {
        "id": "anomaly_detector",
        "name": "Anomaly Detection 異常員工識別",
        "description": "K-Means 無監督離群檢測 + PCA 降維可視化，標記行為異常員工供 HR 複核",
        "icon": "🔍", "color": "#f59e0b",
        "inputs": ["text"],
        "outputs": ["result"],
        "output_labels": {"result": "異常檢測結果"},
        "category": "process",
        "config_schema": [
            {"key": "performance", "label": "績效評分(1~5)", "type": "number"},
            {"key": "overtime_hours", "label": "月加班時長(小時)", "type": "number"},
            {"key": "tenure", "label": "工齡(年)", "type": "number"},
            {"key": "monthly_salary", "label": "月薪資(元)", "type": "number"},
        ],
    },
]

TOOLS_BY_ID = {t["id"]: t for t in TOOLS}
INPUT_TOOLS = [t for t in TOOLS if t["category"] == "input"]
PROCESS_TOOLS = [t for t in TOOLS if t["category"] == "process"]
OUTPUT_TOOLS = [t for t in TOOLS if t["category"] == "output"]
ALL_TOOLS = INPUT_TOOLS + PROCESS_TOOLS + OUTPUT_TOOLS
